### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by wwwdrt** [Braingenius2/Portfolio-website#5]
### 👋 Hello Fortune
- [ ] Instead of using fixed pixel values, consider using responsive units such as rem or em to ensure scalability and flexibility.
- [ ] To position images, consider using background-position with the values of top right or bottom left.
- [ ] Experiment with adjusting the width property and testing whether setting it to 100% of the container resolves any issues.

#### By Jorge Prada, Vishal Kumar, and Juan Velez👍

**Comment by Braingenius2** [comment]
Thanks so much, guys. I implemented the changes you required
